version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Intalling yarn...
      - npm install -g yarn
  pre_build:
    commands:
      - cd ./my-app
      - echo Installing npm packages... 
      - yarn install
  build:
    commands:
      - echo run tests...
      - CI=true yarn run test --reporters=default --reporters=jest-junit
reports:
  jest_reports:
    files:
      - junit.xml
    file-format: JUNITXML
    base-directory: my-app